name: Deploy to VPS

on:
  push:
    branches:
      - master

jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: Deploy using ssh
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.SSH_TOKEN }}
          port: 22
          script: |
            cd /root/discord.ts/shinex/
            git pull
            git status
            pnpm install
            pm2 reload ${{secrets.PM2_NAME}}
